export const CREATE_FORM_ELEMENT = "CREATE_FORM_ELEMENT";
export const EDIT_FORM_ELEMENT = "EDIT_FORM_ELEMENT";
export const DELETE_FORM_ELEMENT = "DELETE_FORM_ELEMENT";
export const FETCH_FORM = "FETCH_FORM";

export const FETCH_USER = "FETCH_USER";
